### ISSUE TITLE
Dica do lameco

### ISSUE THREAD

**Issue by lamecksilva** [gayapedro/testApi#1]
## Dica do lameco

Na pasta raiz do repositório, delete a pasta `node_modules`, e execute o seguinte comando: 
```sh $ echo node_modules >> .gitignore```

Fazendo isto, o git não fará commit ou push das dependências do projeto (pasta `node_modules`), e seu repositório ficará mais organizado.

![image](https://user-images.githubusercontent.com/31391753/53857007-60f6e580-3fb3-11e9-9453-30a163df1b5c.png)

Até a proxima

**Comment by MendesWashington** [comment]
Muito bacana.
